name: flutter_beacon_example
description: Demonstrates how to use the flutter_beacon plugin.
publish_to: 'none'
version: 2.0.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_beacon:
    path: ../
  get: ^4.6.6
  logging: ^1.2.0
  test_api: ^0.7.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
