name: flutter_beacon
description: Flutter plugin for scanning and transmit as beacon (iBeacon) on Android and iOS.
version: 0.5.1
homepage: https://github.com/alann-maulana/flutter_beacon

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterbeacon
        pluginClass: FlutterBeaconPlugin
      ios:
        pluginClass: FlutterBeaconPlugin
      macos:
        pluginClass: FlutterBeaconPlugin
